# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maskrcnn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='maskrcnn.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emaskrcnn.proto\"\"\n\x0fMaskRCNNRequest\x12\x0f\n\x07\x62_image\x18\x01 \x01(\x0c\"q\n\x10MaskRCNNResponse\x12\x0e\n\x06\x62_rois\x18\x01 \x01(\x0c\x12\x13\n\x0b\x62_class_ids\x18\x02 \x01(\x0c\x12\x15\n\rb_class_names\x18\x03 \x01(\x0c\x12\x10\n\x08\x62_scores\x18\x04 \x01(\x0c\x12\x0f\n\x07\x62_masks\x18\x05 \x01(\x0c\x32=\n\x08MaskRCNN\x12\x31\n\x08maskrcnn\x12\x10.MaskRCNNRequest\x1a\x11.MaskRCNNResponse\"\x00\x62\x06proto3'
)




_MASKRCNNREQUEST = _descriptor.Descriptor(
  name='MaskRCNNRequest',
  full_name='MaskRCNNRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='b_image', full_name='MaskRCNNRequest.b_image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=52,
)


_MASKRCNNRESPONSE = _descriptor.Descriptor(
  name='MaskRCNNResponse',
  full_name='MaskRCNNResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='b_rois', full_name='MaskRCNNResponse.b_rois', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b_class_ids', full_name='MaskRCNNResponse.b_class_ids', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b_class_names', full_name='MaskRCNNResponse.b_class_names', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b_scores', full_name='MaskRCNNResponse.b_scores', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b_masks', full_name='MaskRCNNResponse.b_masks', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['MaskRCNNRequest'] = _MASKRCNNREQUEST
DESCRIPTOR.message_types_by_name['MaskRCNNResponse'] = _MASKRCNNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MaskRCNNRequest = _reflection.GeneratedProtocolMessageType('MaskRCNNRequest', (_message.Message,), {
  'DESCRIPTOR' : _MASKRCNNREQUEST,
  '__module__' : 'maskrcnn_pb2'
  # @@protoc_insertion_point(class_scope:MaskRCNNRequest)
  })
_sym_db.RegisterMessage(MaskRCNNRequest)

MaskRCNNResponse = _reflection.GeneratedProtocolMessageType('MaskRCNNResponse', (_message.Message,), {
  'DESCRIPTOR' : _MASKRCNNRESPONSE,
  '__module__' : 'maskrcnn_pb2'
  # @@protoc_insertion_point(class_scope:MaskRCNNResponse)
  })
_sym_db.RegisterMessage(MaskRCNNResponse)



_MASKRCNN = _descriptor.ServiceDescriptor(
  name='MaskRCNN',
  full_name='MaskRCNN',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=169,
  serialized_end=230,
  methods=[
  _descriptor.MethodDescriptor(
    name='maskrcnn',
    full_name='MaskRCNN.maskrcnn',
    index=0,
    containing_service=None,
    input_type=_MASKRCNNREQUEST,
    output_type=_MASKRCNNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASKRCNN)

DESCRIPTOR.services_by_name['MaskRCNN'] = _MASKRCNN

# @@protoc_insertion_point(module_scope)
